name: nf-purple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    name: Job to run the test workflow
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/
      - name: Pull Docker image and cache
        run: |
          docker pull papaemmelab/purple:v0.1.1
          docker pull quay.io/biocontainers/hmftools-sage:3.4.4--hdfd78af_0
      - name: Run unit tests of each process for Amber, Cobalt, binCobalt, Sage, Purple
        id: run_test
        run: |
          nf-test test --ci --config tests/nf-test.matched.config --coverage