name: nf-all-classifiers CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    name: Job to run the test workflow
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/
      - name: Pull Docker image and cache
        run: |
          docker pull papaemmelab/purple:v0.1.0
      - name: Run test data
        run: |
          # nf-test run tests/workflow.test
          
          nextflow run main.nf -profile cloud \
            --tumor TEST \
            --tumorBam tests/data/tumor/tumor.bam \
            --refGenome tests/data/ref/genome.fasta \
            --loci /data/copy_number/GermlineHetPon.37.vcf.gz \
            --gcProfile /data/copy_number/GC_profile.1000bp.37.cnp \
            --diploidRegions /data/copy_number/DiploidRegions.37.bed.gz \
            --ensemblDataDir /data/common/common \
            --genomeVersion V37 \
            --outdir /app/results \
            --cores 4
      - name: Check result
        run: |
          if [ ! -f /app/results/TEST.purple.purity.tsv ]; then
            echo "Result 'TEST.purple.purity.tsv' does not exist"
            exit 1
          fi