name: nf-purple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    name: Job to run the test workflow
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/
      - name: Pull Docker image and cache
        run: |
          docker pull papaemmelab/purple:v0.1.0
      - name: Run test data
        run: |
          nextflow run main.nf -profile cloud \
            --tumor TEST \
            --tumorBam tests/data/tumor.bam \
            --refGenome tests/data/reference.fasta \
            --outdir /app/results
      - name: Check result
        run: |
          if [ ! -f /app/results/TEST.purple.purity.tsv ]; then
            echo "Result 'TEST.purple.purity.tsv' does not exist"
            exit 1
          fi